name: Build and Release APK

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Generate Hive adapters
      run: flutter pub run build_runner build --delete-conflicting-outputs
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Rename APK
      run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/wms-testing-v${{ github.run_number }}.apk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: wms-testing-apk
        path: build/app/outputs/flutter-apk/wms-testing-v${{ github.run_number }}.apk
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/wms-testing-v${{ github.run_number }}.apk
        body: |
          ## WMS Testing App - Release
          
          ### 📱 Установка
          1. Скачайте APK файл ниже
          2. Разрешите установку из неизвестных источников на Android
          3. Установите приложение
          
          ### ✨ Что нового
          - Flutter приложение с Clean Architecture
          - 25 вопросов по WMS системам
          - Локальное хранилище с Hive
          - Material Design 3 тема (светлая/тёмная)
          - Статистика результатов
          
          ### 📚 Функции
          - Тестирование знаний по WMS
          - 15+ категорий вопросов
          - 4 уровня сложности
          - Отслеживание прогресса
          - История результатов
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Development Release (on push to main)
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-build-${{ github.run_number }}
        name: Development Build ${{ github.run_number }}
        prerelease: true
        files: build/app/outputs/flutter-apk/wms-testing-v${{ github.run_number }}.apk
        body: |
          ## 🔧 Development Build ${{ github.run_number }}
          
          Автоматическая сборка из ветки main.
          
          ### 📱 Скачать и установить
          1. Скачайте APK файл ниже
          2. Разрешите установку из неизвестных источников
          3. Установите приложение
          
          **⚠️ Это тестовая сборка - могут быть баги!**
          
          ### Последний коммит
          ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
